CREATE TABLE `stats` (
	`id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
	`Name` VARCHAR(512) NULL DEFAULT NULL COLLATE 'utf8mb4_bin',
	`SourceID` VARCHAR(32) NULL DEFAULT NULL COLLATE 'utf8mb4_bin',
	`FirstLast` VARCHAR(512) NULL DEFAULT NULL COLLATE 'utf8mb4_bin',
	`Citizenid` VARCHAR(32) NULL DEFAULT NULL COLLATE 'utf8mb4_bin',
	`MoneyTotal` LONGTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_bin',
	`Job` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_bin',
	`JobLabel` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_bin',
	`OnDuty` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_bin',
	`date_recorded` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
)
COLLATE='utf8mb4_bin'
ENGINE=InnoDB
AUTO_INCREMENT=422955
;
